const data = [
  {
    title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    prevPrice: 109.95,
    newPrice: 67,
    category: "men clothing",
    img: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    star: 3,
  },
  {
    title: "Mens Casual Premium Slim Fit T-Shirts",
    prevPrice: 322.3,
    newPrice: 316.2,
    category: "men clothing",
    img: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    star: 4,
  },
  {
    title: "Mens Cotton Jacket",
    prevPrice: 255.99,
    newPrice: 242.1,
    category: "men clothing",
    img: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    star: 1,
  },
  {
    title: "Mens Casual Slim Fit",
    prevPrice: 85.99,
    newPrice: 69.9,
    category: "men clothing",
    img: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    star: 3,
  },
  {
    title:
      "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    prevPrice: 695,
    newPrice: 530,
    category: "jewelery",
    img: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    star: 5,
  },
  {
    title: "Solid Gold Petite Micropave",
    prevPrice: 368,
    newPrice: 317,
    category: "jewelery",
    img: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    star: 3,
  },
  {
    title: "White Gold Plated Princess",
    prevPrice: 229.99,
    newPrice: 148.5,
    category: "jewelery",
    img: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    star: 5,
  },
  {
    title: "Pierced Owl Rose Gold Plated Stainless Steel Double",
    prevPrice: 210.99,
    newPrice: 180.99,
    category: "jewelery",
    img: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    star: 2,
  },
  {
    title: "WD 2TB Elements Portable External Hard Drive - USB 3.0",
    prevPrice: 364,
    newPrice: 259,
    category: "electronics",
    img: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    star: 4,
  },
  {
    title: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    prevPrice: 309,
    newPrice: 248,
    category: "electronics",
    img: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    star: 5,
  },
  {
    title:
      "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    prevPrice: 709,
    newPrice: 691,
    category: "electronics",
    img: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    star: 2,
  },
  {
    title:
      "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    prevPrice: 814,
    newPrice: 702,
    category: "electronics",
    img: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    star: 4,
  },
  {
    title: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
    prevPrice: 599,
    newPrice: 540,
    category: "electronics",
    img: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    star: 1,
  },
  {
    title: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA)",
    prevPrice: 999.99,
    newPrice: 956.3,
    category: "electronics",
    img: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    star: 2,
  },
  {
    title: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
    prevPrice: 56.99,
    newPrice: 44,
    category: "women clothing",
    img: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    star: 4,
  },
  {
    title:
      "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
    prevPrice: 129.95,
    newPrice: 123,
    category: "women clothing",
    img: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    star: 1,
  },
  {
    title: "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
    prevPrice: 339.99,
    newPrice: 334,
    category: "women clothing",
    img: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    star: 2,
  },
  {
    title: "MBJ Women's Solid Short Sleeve Boat Neck V",
    prevPrice: 79.85,
    newPrice: 67.5,
    category: "women clothing",
    img: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    star: 3,
  },
  {
    title: "Opna Women's Short Sleeve Moisture",
    prevPrice: 97.95,
    newPrice: 66.5,
    category: "women clothing",
    img: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    star: 5,
  },
  {
    title: "DANVOUY Womens T Shirt Casual Cotton Short",
    prevPrice: 212.99,
    newPrice: 210.45,
    category: "women clothing",
    img: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    star: 4,
  },
];

export default data;
